#!/usr/bin/env python3

import sys
import json
import urllib.request
from lib_dropbox import Dropbox
from init import init


settings, argv = init()
token = settings['token']
path = argv[0] if len(argv) > 0 else ""

api = Dropbox(token)
for item in api.dropbox_list_folder(path):
    if item['.tag'] == "folder":
        item = dict(item, name=item['name'] + "/", size="-", server_modified="-")
        print("{id} {server_modified: >20} {size: >16} {name}".format(**item))
    elif item['.tag'] == "file":
        print("{id} {server_modified: >20} {size: >16} {name}".format(**item))
    else:
        print("unknown:", item)


